import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../../../app/app_form_styles.dart';
import '../dashboard_models.dart';

class ValueCard extends StatelessWidget {
  final ValueData value;

  const ValueCard({
    super.key,
    required this.value,
  });

  @override
  Widget build(BuildContext context) {
    final currency = NumberFormat.currency(symbol: '\$', decimalDigits: 2);

    return _Panel(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Deposit Value',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w800,
              color: appPrimaryTextColor(context),
              decoration: TextDecoration.none,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            'Financial impact generated by verified users',
            style: TextStyle(
              fontSize: 14,
              color: appSecondaryTextColor(context),
              decoration: TextDecoration.none,
            ),
          ),
          const SizedBox(height: 20),
          _RowItem(
            label: 'Total Verified',
            value: currency.format(value.totalVerified),
          ),
          _RowItem(
            label: 'Average Verified',
            value: currency.format(value.averageVerified),
          ),
          _RowItem(
            label: 'Median P50',
            value: currency.format(value.p50Verified),
          ),
          _RowItem(
            label: 'P90 Verified',
            value: currency.format(value.p90Verified),
          ),
          _RowItem(
            label: 'Qualified ≥500',
            value: '${value.qualified500}',
          ),
        ],
      ),
    );
  }
}

class _RowItem extends StatelessWidget {
  final String label;
  final String value;

  const _RowItem({
    required this.label,
    required this.value,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Row(
        children: [
          Expanded(
            child: Text(
              label,
              style: TextStyle(
                color: appSecondaryTextColor(context),
                fontWeight: FontWeight.w600,
                decoration: TextDecoration.none,
              ),
            ),
          ),
          Text(
            value,
            style: TextStyle(
              color: appPrimaryTextColor(context),
              fontWeight: FontWeight.w900,
              decoration: TextDecoration.none,
            ),
          ),
        ],
      ),
    );
  }
}

class _Panel extends StatelessWidget {
  final Widget child;

  const _Panel({
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: appCardBackgroundColor(context),
        borderRadius: BorderRadius.circular(24),
        border: Border.all(
          color: appBorderColor(context),
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(
              appIsDarkMode(context) ? 0.18 : 0.04,
            ),
            blurRadius: 18,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: child,
    );
  }
}